// ========================================================================================
// 国际化内容数据 - 完整的多语言文本内容
// ========================================================================================

export const contentData = {
    en: {
        home: {
            name: 'Hua Wang',
            title: 'Full Stack Developer',
            slogan: 'Order from Chaos. Innovation through Tradeoffs...',
        },
        about: {
            pages: [
                {
                    id: 'statement',
                    title: 'Personal Statement',
                    content: {
                        greeting: "Kia ora, I'm Hua Wang",
                        paragraphs: [
                            'I am a full-stack developer with over a decade of experience, from early work with PHP to today’s modern React ecosystems. My journey spans enterprise websites, CMS platforms, internal systems, and data-driven apps, enriched by a passion for computer graphics, where I blend shaders, lighting, and generative effects into the web.',
                            'What drives me is the process: turning scattered user stories into clarity, navigating complexity with an agnostic mindset toward languages and frameworks, and building solutions that balance logic with creativity. To me, code is not just function but also expression, where design, implementation, and narrative converge.',
                            'Beyond frontend and backend development, I explore DevOps, containerization, and cloud platforms, while my Master’s in Data Science deepens my grasp of algorithms and data pipelines. To me, development is about seeking order in chaos and finding innovation in every trade-off.',
                        ],
                    },
                },
            ],
        },
        projects: {
            title: 'My Projects',
            subtitle: 'Showcases',
            bottomSubtitle: 'Each project represents a unique challenge and learning journey',
            description:
                'From Full Stack Web Development to 3D immersive experiences, from computer science to data science, to computer graphics — explore the diverse technology and solutions. Language, platform, framework agnostic.',
            viewProject: 'View Project',
            viewAction: 'View',
            technologies: 'Technologies',
            totalProjects: 'Total Projects',
            exploreMap: 'Map View',
            exploreMapTooltip: 'Explore Projects on Interactive Map',
            showing: 'Showing',
            viewDetails: 'View Details',
            liveDemo: 'Live Demo',
            officialSite: 'Official',
            githubRepo: 'GitHub',
            learnMore: 'Learn more',
            // 项目详情相关文本
            detail: {
                technologyStack: 'Technology Stack',
                projectStatistics: 'Project Statistics',
                subProjects: 'Sub Projects',
                visitSite: 'Visit Site',
                closeModal: 'Close modal',
            },
            // 项目过滤相关文本
            filter: {
                allProjects: 'All Projects',
                all: 'All',
                other: 'Other',
            },
            // 地图相关文本
            map: {
                resetToDefaultView: 'Reset to default view',
                closeMap: 'Close map',
                title: 'Mapping Myself',
                zoomIn: 'Zoom in',
                zoomOut: 'Zoom out',
                locateMe: 'Locate me',
                categories: 'Categories',
            },
        },
        gallery: {
            // 移动端画廊配置
            mobile: {
                title: 'Gallery',
                subtitle: 'Each photo carries unique stories.',
                tapHint: 'Tap images to view full size',
                loadingMore: 'Loading more...',
                showing: 'Showing',
                images: 'images',
                tapToView: 'Tap to view full size',
                noContent: 'No gallery items available',
                tryAgain: 'Please try again later',
                mobileNotice: {
                    title: 'Mobile Experience Notice',
                    description:
                        'The 3D gallery uses first-person navigation technology requiring keyboard and mouse controls. For the best experience, we recommend using a desktop device.',
                    viewGallery: 'View Image Gallery',
                    desktopHint: 'Or visit on desktop for the full 3D gallery experience',
                },
            },
            // 3D Gallery 配置
            gallery3D: {
                title: 'Corridor of Light and Shadow',
                subtitle: 'Immersive 3D Art Experience',
                description:
                    'Enter a professionally curated virtual gallery space showcasing visual works in an interactive 3D environment.',
                instructions: {
                    clickToStart: 'Click to enter the gallery',
                    howToPlay: 'How to Play?',
                    clickToEnter: 'Click to enter the gallery',
                    mouseControl: 'Mouse - Look around and explore',
                    keyboardControl: 'Move through the gallery',
                    escapeControl: 'Exit pointer lock mode',
                    navigation: {
                        movement: 'Movement Navigation',
                        wasd: 'WASD / Arrow Keys - Move through the gallery',
                        mouse: 'Mouse - Look around and explore',
                        esc: 'ESC - Exit pointer lock mode',
                    },
                    experience: {
                        title: 'Gallery Features',
                        lighting: 'Professional museum lighting system',
                        layout: 'Curated artwork placement and spacing',
                        interaction: 'First-person exploration experience',
                    },
                },
            },
        },
        education: {
            title: 'Education',
            subtitle: 'Academic Background',
            labels: {
                academicRecords: 'Academic Records',
                totalCredits: 'Total Credits',
                gpa: 'GPA',
                totalCourses: 'Total Courses',
                capstoneProjects: 'Capstone Projects',
                academicAwards: 'Academic Awards',
                academicExcellenceAward: 'Academic Excellence Award',
                withDistinction: 'with Distinction',
                level: 'Level',
                credits: 'Credits',
            },
            degrees: [
                {
                    id: 'masters',
                    degree: 'Master of Applied Data Science',
                    degreeHonor: true,
                    institution: 'University of Canterbury',
                    location: 'Christchurch, New Zealand',
                    period: 'Feb 2024 - Feb 2025',
                    logo: '/education/unicanterburylogo.png',
                    gpa: 'A average',
                    totalCredits: 180,
                    courses: [
                        {
                            year: '2024',
                            semester: 'Semester 1',
                            courses: [
                                {
                                    code: 'DATA401',
                                    name: 'Introduction to Data Science',
                                    credits: 15,
                                    grade: 'A',
                                    level: 4,
                                },
                                {
                                    code: 'DIGI405',
                                    name: 'Texts, Discourses and Data: the Humanities and Data Science',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 4,
                                },
                                {
                                    code: 'DATA472',
                                    name: 'Based cloud computing and infrastructure data engineering',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 4,
                                },
                                {
                                    code: 'DATA416',
                                    name: 'Contemporary Issues in Data Science',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 4,
                                },
                            ],
                        },
                        {
                            year: '2024',
                            semester: 'Semester 2',
                            courses: [
                                {
                                    code: 'COSC473',
                                    name: 'Decentralised Applications on the Web',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 4,
                                },
                                {
                                    code: 'COSC440',
                                    name: 'Deep Learning',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 4,
                                },
                                {
                                    code: 'DATA420',
                                    name: 'Scalable Data Science',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 4,
                                },
                                {
                                    code: 'DATA415',
                                    name: 'Computational Social Choice',
                                    credits: 15,
                                    grade: 'A',
                                    level: 4,
                                },
                                {
                                    code: 'GISC412',
                                    name: 'Spatial Data Science',
                                    credits: 15,
                                    grade: 'A',
                                    level: 4,
                                },
                            ],
                        },
                        {
                            year: '2024 - 2025',
                            semester: 'Summer',
                            courses: [
                                {
                                    code: 'DATA605',
                                    name: 'Applied Data Science Industry Research Project · Zespri International',
                                    credits: 45,
                                    grade: 'A+',
                                    level: 6,
                                },
                            ],
                        },
                    ],
                    capstoneProjects: [
                        {
                            name: 'SwapBytes',
                            description:
                                'A P2P file-sharing and messaging app built using Rust (backend) and React with Tauri (frontend). Integrated libp2p for decentralised networking.',
                            technologies: ['Rust', 'React', 'Tauri', 'libp2p'],
                            githubUrl: 'https://github.com/aemooooon/swapbytes',
                            image: '/education/swapbytes.jpg',
                        },
                        {
                            name: 'Digital Pet',
                            description:
                                'A blockchain-based virtual pet dApp on Secret Network. Built a CosmWasm smart contract using Rust and a React frontend.',
                            technologies: ['Rust', 'CosmWasm', 'React', 'Secret Network'],
                            githubUrl: 'https://github.com/aemooooon/digital-pet',
                            image: '/education/digitalpet.jpg',
                        },
                        {
                            name: 'ECAN Data Pipeline',
                            description:
                                'A collaborative cloud-based automation system for collecting and processing environmental data from 17 different sources.',
                            technologies: ['Apache Airflow', 'Python', 'GraphQL', 'AWS'],
                            githubUrl:
                                'https://github.com/aemooooon/DATA472-Individual-Project-Submission',
                            image: '/education/ecan.jpg',
                        },
                    ],
                },
                {
                    id: 'bachelors',
                    degree: 'Bachelor of Information Technology',
                    degreeHonor: true,
                    institution: 'Otago Polytechnic',
                    location: 'Dunedin, New Zealand',
                    period: 'July 2017 - June 2021',
                    logo: '/education/otago-polytechnic-vertical-blue.svg',
                    gpa: 'A average',
                    totalCredits: 360,
                    courses: [
                        {
                            year: '2017',
                            semester: 'Year 1',
                            courses: [
                                {
                                    code: 'IN501001',
                                    name: 'Professional Practice for Information Technology',
                                    credits: 15,
                                    grade: 'B+',
                                    level: 5,
                                },
                                {
                                    code: 'IN510001',
                                    name: 'Programming 1',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN520001',
                                    name: 'PC Maintenance',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN521001',
                                    name: 'Maths For IT',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                            ],
                        },
                        {
                            year: '2018',
                            semester: 'Year 2',
                            courses: [
                                {
                                    code: 'IN505001',
                                    name: 'Introduction to Systems Analysis',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN511001',
                                    name: 'Programming 2',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN512001',
                                    name: 'Web 1 - Technology and Development',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN515001',
                                    name: 'Introduction to Networks',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN605001',
                                    name: 'Databases 2',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN610001',
                                    name: 'Programming 3',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN612001',
                                    name: 'Web 2 - Programming',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN617001',
                                    name: 'Linux Operating Systems - Ubuntu',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                            ],
                        },
                        {
                            year: '2019',
                            semester: 'Year 3',
                            courses: [
                                {
                                    code: 'IN602001',
                                    name: 'Software Engineering',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 6,
                                },
                                {
                                    code: 'IN628002',
                                    name: 'Programming 4',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN700001',
                                    name: 'Project 1',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN705002',
                                    name: 'Databases 3',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN711001',
                                    name: 'Algorithms and Data Structures',
                                    credits: 15,
                                    grade: 'A',
                                    level: 7,
                                },
                                {
                                    code: 'IN712001',
                                    name: 'Web 3 - Enterprise Development',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 7,
                                },
                                {
                                    code: 'IN719001',
                                    name: 'Systems Administration',
                                    credits: 15,
                                    grade: 'A',
                                    level: 7,
                                },
                                {
                                    code: 'IN720001',
                                    name: 'Administering a Virtual Infrastructure',
                                    credits: 15,
                                    grade: 'A',
                                    level: 7,
                                },
                            ],
                        },
                        {
                            year: '2021',
                            semester: 'Year 4',
                            courses: [
                                {
                                    code: 'IN608001',
                                    name: 'Intermediate Application Development Concepts',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN721001',
                                    name: 'Mobile Application Development',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN730151',
                                    name: 'Year Three Special Topic',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN732001',
                                    name: 'Studio 6',
                                    credits: 15,
                                    grade: 'Passed',
                                    level: 7,
                                },
                            ],
                        },
                    ],
                    awards: [
                        {
                            title: 'Academic Excellence & Best Programmer',
                            year: '2021',
                            image: '/education//awared-best-programmer.jpg',
                        },
                        {
                            title: 'Excellence in the Bachelor of Information Technology',
                            year: '2019',
                            image: '/education/awared-excellence.jpg',
                        },
                    ],
                    capstoneProjects: [
                        {
                            name: 'Travel Assistant',
                            description:
                                'An Android app using Kotlin, Jetpack, Google Maps, and Room DB for trip planning.',
                            technologies: ['Kotlin', 'Android', 'Google Maps'],
                            githubUrl: 'https://github.com/aemooooon/travel-assistant',
                            image: '/travelassistant/ta02.jpg',
                        },
                        {
                            name: 'FitsGo',
                            description:
                                'A Fitness tracker app built with React Native and Firebase, supporting location tracking and workout history.',
                            technologies: ['React Native', 'Firebase'],
                            githubUrl: 'https://github.com/aemooooon/fitsgo',
                            image: '/fitsgo/fitsgo.02.jpg',
                        },
                    ],
                },
            ],
        },
        contact: {
            title: 'Get In Touch',
            subtitle: 'Looking forward to hearing from you',
            description: 'Connect for opportunities, collaborations, or just to say hello.',
            location: 'Christchurch, New Zealand',
            emailAddress: 'aemooooon@gmail.com',
            phone: '+64 21 *** 0520',
            connectWithMe: 'Connect with me',
            lookingForward: 'Copyright © 2025 Hua Wang',
            contactMethods: {
                email: {
                    title: 'Email',
                    description: 'Send me an email',
                },
                phone: {
                    title: 'Phone',
                    description: 'Give me a call',
                },
                wechat: {
                    title: 'WeChat',
                    description: 'Connect via WeChat',
                    id: 'Aemooooon',
                },
                location: {
                    title: 'Location',
                    description: 'Based in Christchurch',
                },
            },
            social: {
                github: {
                    url: 'https://github.com/aemooooon',
                    label: 'GitHub',
                },
                linkedin: {
                    url: 'https://www.linkedin.com/in/aemonwang',
                    label: 'LinkedIn',
                },
                email: {
                    url: 'mailto:aemooooon@gmail.com',
                    label: 'Email',
                },
            },
        },
        ui: {
            language: 'Language',
            theme: 'Theme',
            light: 'Light',
            dark: 'Dark',
            audio: 'Audio',
            play: 'Play',
            pause: 'Pause',
            mute: 'Mute',
            unmute: 'Unmute',
            loading: 'Loading...',
            backToHome: 'Back to Home',
            darkMode: 'Dark Mode',
            lightMode: 'Light Mode',
            toggleTheme: 'Toggle Theme',
            mobileScrollHint: 'scroll down to explore...',
        },
    },
    zh: {
        home: {
            name: '王华',
            title: '全栈工程师',
            slogan: '驭混沌而立秩序；执中庸以启新象。',
        },
        about: {
            pages: [
                {
                    id: 'statement',
                    content: {
                        greeting: '你好，我是王华',
                        paragraphs: [
                            '夫天地演数，阴阳化爻，臣以一介码农，躬耕于比特之野十载有余。初习jQuery古法，今研React新道，历经诸侯之网站，掌CMS之枢机，筑内廷之系统，驭数据于方寸。然臣心向星辰，醉心图形之域，每有涉猎，必穷Shader之变，究光影之妙，合生成之艺于万维网中，此臣技之所寄也。',
                            '臣闻《易》云：“形而上者谓之道，形而下者谓之器。”臣之所驱，正在道器相融：散落之用户故事，臣析为清明；纷杂之技术桎梏，臣以无执之心破之。盖语言框架，不过器物；逻辑创造，方见精神。是故代码非止于功用，亦载文心，融设计、实现与叙事于一炉，犹《诗》之兴观群怨，皆可托于数行之间。',
                            '臣虽主营前后二端，然未尝忘怀运维之策、容器之术与云之平台。更修数据科学之硕学，深研算法之精微，管道之纤畅。诚如《道德经》所言：“图难于其易，为大于其细”，臣每日所行，皆在混沌中求秩序，于权衡处创新篇——此乃臣平生之志也。',
                            '今托心于代码，寄志于云端，惟愿以技术立命，以创造安身，虽世变时移，此心不易。',
                        ],
                    },
                },
            ],
        },
        projects: {
            title: '累岁所成',
            subtitle: '列艺斯观',
            bottomSubtitle: '每个项目都代表着独特的挑战和学习之旅',
            description:
                '从全栈Web开发到3D沉浸式体验，从计算机科学，图形学，到数据科学 — 探索多样的技术与解决方案。',
            viewProject: '查看项目',
            viewAction: '查看',
            technologies: '技术栈',
            totalProjects: '总项目数',
            exploreMap: '地图',
            exploreMapTooltip: '在交互地图上探索项目',
            showing: '显示',
            viewDetails: '查看详情',
            liveDemo: '在线演示',
            officialSite: '官方',
            githubRepo: '源码',
            learnMore: '了解更多',
            // 项目详情相关文本
            detail: {
                technologyStack: '技术栈',
                projectStatistics: '项目统计',
                subProjects: '子项目',
                visitSite: '访问网站',
                closeModal: '关闭弹窗',
            },
            // 项目过滤相关文本
            filter: {
                allProjects: '全部项目',
                all: '全部',
                other: '其他',
            },
            // 地图相关文本
            map: {
                resetToDefaultView: '重置到默认视图',
                closeMap: '关闭地图',
                title: '足迹',
                zoomIn: '放大',
                zoomOut: '缩小',
                locateMe: '定位我的位置',
                categories: '项目类别',
            },
        },
        gallery: {
            title: '照片画廊',
            subtitle: '通过视觉展示我的工作和经历',
            description: '精心策划的视觉项目和创意作品集合。',
            viewImage: '查看图片',
            // 移动端画廊配置
            mobile: {
                title: '作品集',
                subtitle: '记录生活中的美好瞬间，每一张照片都承载着独特的故事与回忆。',
                tapHint: '点击图片查看大图',
                loadingMore: '加载更多图片...',
                showing: '已显示',
                images: '张图片',
                tapToView: '点击查看大图',
                noContent: '暂无图片内容',
                tryAgain: '请稍后再试',
                mobileNotice: {
                    title: '移动端体验提示',
                    description:
                        '3D 画廊采用第一人称漫游技术，需要键盘和鼠标操作，移动端体验可能不佳。建议使用桌面设备以获得最佳浏览效果。',
                    viewGallery: '继续浏览图片集',
                    desktopHint: '或在桌面设备上体验完整的 3D 画廊',
                },
            },
            // 3D Gallery 配置
            gallery3D: {
                title: '浮生长廊',
                subtitle: '沉浸式3D艺术体验',
                description: '步入专业策展的虚拟画廊空间，在交互式3D环境中欣赏视觉作品。',
                instructions: {
                    clickToStart: '点击进入',
                    howToPlay: '如何操作？',
                    clickToEnter: '点击进入长廊',
                    mouseControl: '鼠标 - 环视周围，探索画作',
                    keyboardControl: '移动穿行长廊',
                    escapeControl: '退出指针锁定模式',
                    navigation: {
                        movement: '移动导航',
                        wasd: 'WASD / 方向键 - 在画廊中移动',
                        mouse: '鼠标 - 环视和探索',
                        esc: 'ESC - 退出指针锁定模式',
                    },
                    experience: {
                        title: '画廊特色',
                        lighting: '专业美术馆照明系统',
                        layout: '精心策划的艺术品布局',
                        interaction: '第一人称沉浸式体验',
                    },
                },
            },
        },
        education: {
            title: '修业之路',
            subtitle: '杏坛踪迹',
            labels: {
                academicRecords: '学术记录',
                totalCredits: '总学分',
                gpa: '平均成绩',
                totalCourses: '课程总数',
                capstoneProjects: '毕业项目',
                academicAwards: '学术奖项',
                academicExcellenceAward: '学术优秀奖',
                withDistinction: '优等荣誉',
                level: '等级',
                credits: '学分',
            },
            degrees: [
                {
                    id: 'masters',
                    degree: '应用数据科学硕士学位',
                    degreeHonor: true,
                    institution: '坎特伯雷大学',
                    location: '基督城',
                    period: '2024年2月 - 2025年2月',
                    logo: '/education/unicanterburylogo.png',
                    gpa: 'A',
                    totalCredits: 180,
                    courses: [
                        {
                            year: '2024',
                            semester: '第一学期',
                            courses: [
                                {
                                    code: 'DATA401',
                                    name: '数据科学导论',
                                    credits: 15,
                                    grade: 'A',
                                    level: 4,
                                },
                                {
                                    code: 'DATA416',
                                    name: '数据科学当代问题',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 4,
                                },
                                {
                                    code: 'DIGI405',
                                    name: '人文学科与数据科学',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 4,
                                },
                                {
                                    code: 'DATA472',
                                    name: '基于云基础架构的数据工程',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 4,
                                },
                            ],
                        },
                        {
                            year: '2024',
                            semester: '第二学期',
                            courses: [
                                {
                                    code: 'COSC473',
                                    name: 'Web3，区块链及去中心化应用',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 4,
                                },
                                {
                                    code: 'DATA420',
                                    name: '可扩展数据科学',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 4,
                                },
                                {
                                    code: 'COSC440',
                                    name: '深度学习',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 4,
                                },
                                {
                                    code: 'DATA415',
                                    name: '计算社会选择',
                                    credits: 15,
                                    grade: 'A',
                                    level: 4,
                                },
                                {
                                    code: 'GISC412',
                                    name: '空间数据科学',
                                    credits: 15,
                                    grade: 'A',
                                    level: 4,
                                },
                            ],
                        },
                        {
                            year: '2024 Summer',
                            semester: '2024-2025 暑假',
                            courses: [
                                {
                                    code: 'DATA605',
                                    name: '应用数据科学行业研究项目 · 佳沛国际',
                                    credits: 45,
                                    grade: 'A+',
                                    level: 6,
                                },
                            ],
                        },
                    ],
                    capstoneProjects: [
                        {
                            name: 'SwapBytes',
                            description:
                                '使用Rust（后端）和React与Tauri（前端）构建的P2P文件共享和消息应用。集成libp2p进行去中心化网络。',
                            technologies: ['Rust', 'React', 'Tauri', 'libp2p'],
                            githubUrl: 'https://github.com/aemooooon/swapbytes',
                            image: '/education/swapbytes.jpg',
                        },
                        {
                            name: '数字宠物',
                            description:
                                '基于Secret Network的区块链虚拟宠物dApp。使用Rust构建CosmWasm智能合约，React前端。',
                            technologies: ['Rust', 'CosmWasm', 'React', 'Secret Network'],
                            githubUrl: 'https://github.com/aemooooon/digital-pet',
                            image: '/education/digitalpet.jpg',
                        },
                        {
                            name: '坎特伯雷环境部数据管线',
                            description:
                                '协作式云端自动化系统，用于从17个不同来源收集和处理环境数据。',
                            technologies: ['Apache Airflow', 'Python', 'GraphQL', 'AWS'],
                            githubUrl:
                                'https://github.com/aemooooon/DATA472-Individual-Project-Submission',
                            image: '/education/ecan.jpg',
                        },
                    ],
                },
                {
                    id: 'bachelors',
                    degree: '信息技术学士学位',
                    degreeHonor: true,
                    institution: '奥塔哥理工学院',
                    location: '达尼丁',
                    period: '2017年7月 - 2021年6月',
                    logo: '/education/otago-polytechnic-vertical-blue.svg',
                    gpa: 'A',
                    totalCredits: 360,
                    courses: [
                        {
                            year: '2017',
                            semester: '第一年',
                            courses: [
                                {
                                    code: 'IN501001',
                                    name: '信息技术专业实践',
                                    credits: 15,
                                    grade: 'B+',
                                    level: 5,
                                },
                                {
                                    code: 'IN510001',
                                    name: '程序设计 1',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN520001',
                                    name: '计算机维护',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN521001',
                                    name: 'IT数学',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                            ],
                        },
                        {
                            year: '2018',
                            semester: '第二年',
                            courses: [
                                {
                                    code: 'IN505001',
                                    name: '系统分析导论',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN511001',
                                    name: '程序设计 2',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN512001',
                                    name: 'Web技术与开发',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN515001',
                                    name: '网络导论',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 5,
                                },
                                {
                                    code: 'IN605001',
                                    name: '数据库 2',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN610001',
                                    name: '程序设计 3',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN612001',
                                    name: 'Web程序设计',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN617001',
                                    name: 'Linux操作系统',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                            ],
                        },
                        {
                            year: '2019',
                            semester: '第三年',
                            courses: [
                                {
                                    code: 'IN602001',
                                    name: '软件工程',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 6,
                                },
                                {
                                    code: 'IN628002',
                                    name: '程序设计 4',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN700001',
                                    name: '项目 1',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN705002',
                                    name: '数据库 3',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN711001',
                                    name: '算法与数据结构',
                                    credits: 15,
                                    grade: 'A',
                                    level: 7,
                                },
                                {
                                    code: 'IN712001',
                                    name: '企业Web开发',
                                    credits: 15,
                                    grade: 'A-',
                                    level: 7,
                                },
                                {
                                    code: 'IN719001',
                                    name: '系统管理',
                                    credits: 15,
                                    grade: 'A',
                                    level: 7,
                                },
                                {
                                    code: 'IN720001',
                                    name: '虚拟基础设施管理',
                                    credits: 15,
                                    grade: 'A',
                                    level: 7,
                                },
                            ],
                        },
                        {
                            year: '2021',
                            semester: '第四年',
                            courses: [
                                {
                                    code: 'IN608001',
                                    name: '中级应用开发概念',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 6,
                                },
                                {
                                    code: 'IN721001',
                                    name: '移动应用开发',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN730151',
                                    name: '三年级特殊主题',
                                    credits: 15,
                                    grade: 'A+',
                                    level: 7,
                                },
                                {
                                    code: 'IN732001',
                                    name: '工作室 6',
                                    credits: 15,
                                    grade: '通过',
                                    level: 7,
                                },
                            ],
                        },
                    ],
                    awards: [
                        {
                            title: '学术卓越与最佳程序员奖',
                            year: '2021',
                            image: '/education/awared-best-programmer.jpg',
                        },
                        {
                            title: '信息技术学士优秀奖',
                            year: '2019',
                            image: '/education/awared-excellence.jpg',
                        },
                    ],
                    capstoneProjects: [
                        {
                            name: '旅行助手',
                            description:
                                '使用Kotlin、Jetpack、Google Maps和Room DB开发的Android旅行规划应用。',
                            technologies: ['Kotlin', 'Android', 'Google Maps'],
                            githubUrl: 'https://github.com/aemooooon/travel-assistant',
                            image: '/travelassistant/ta02.jpg',
                        },
                        {
                            name: 'FitsGo',
                            description:
                                '使用React Native和Firebase构建的健身追踪应用，支持位置跟踪和锻炼历史。',
                            technologies: ['React Native', 'Firebase'],
                            githubUrl: 'https://github.com/aemooooon/fitsgo',
                            image: '/fitsgo/fitsgo.02.jpg',
                        },
                    ],
                },
            ],
        },
        contact: {
            title: '青鸟殷勤',
            subtitle: '翘盼汝之玉音',
            description: '倘蒙垂询，或谋事，或叙契，一函可达。',
            location: '新西兰',
            emailAddress: 'aemooooon@gmail.com',
            phone: '+64 21 *** 0520',
            connectWithMe: '社交媒体',
            lookingForward: '版权所有 © 2025 王华',
            contactMethods: {
                email: {
                    title: '邮箱',
                    description: '发送邮件',
                },
                phone: {
                    title: '电话',
                    description: '电话联系',
                },
                wechat: {
                    title: '微信',
                    description: '微信联系',
                    id: 'Aemooooon',
                },
                location: {
                    title: '位置',
                    description: '基督之城',
                },
            },
            social: {
                github: {
                    url: 'https://github.com/aemooooon',
                    label: 'GitHub',
                },
                linkedin: {
                    url: 'https://www.linkedin.com/in/aemonwang',
                    label: 'LinkedIn',
                },
                email: {
                    url: 'mailto:aemooooon@gmail.com',
                    label: '邮箱',
                },
            },
        },
        ui: {
            language: '语言',
            theme: '主题',
            light: '浅色',
            dark: '深色',
            audio: '音频',
            play: '播放',
            pause: '暂停',
            mute: '静音',
            unmute: '取消静音',
            loading: '加载中...',
            backToHome: '返回首页',
            darkMode: '深色模式',
            lightMode: '浅色模式',
            toggleTheme: '切换主题',
            mobileScrollHint: '向下滑动探索更多...',
        },
    },
};
