// ========================================================================================
// 足迹数据配置 - 包含我的人生足迹和地理位置信息
// ========================================================================================

export const footprintsData = [
    {
        type: 'work',
        name: 'Orchard Sampling Scheduler',
        client: 'Zespri International',
        coordinates: [-37.7866, 176.4416],
        location: 'Bay of Plenty, New Zealand',
        year: '2024-2025',
        link: 'https://www.zespri.com',
        img: '/zespri/zespri.1.jpg',
    },
    {
        type: 'work',
        name: '3D Saas Platform',
        client: 'Realibox',
        coordinates: [22.9951158, 113.3335372],
        location: 'Guangzhou, China',
        year: '2021-2023',
        link: 'https://hub.realibox.com/',
        img: ['/realibox/official/official.01.jpg'],
    },
    {
        type: 'work',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Chongqing Nuclear Stone Technology',
        coordinates: [29.5638, 106.5505],
        location: 'Chongqing, China',
        year: '2020-2021',
        link: '',
        img: '/vr/htfxj.jpg',
    },
    {
        type: 'project',
        name: 'Real-time Air Quality Index Publish Platform',
        client: 'Enshi Environmental Agency',
        coordinates: [30.311395, 109.4795951],
        location: 'Enshi, Hubei, China',
        year: '2020',
        links: {
            live: 'https://aqi.eseemc.cn/',
        },
        img: '/aqi/aqi06.jpg',
    },
    {
        type: 'education',
        name: 'Master of Applied Data Science',
        client: 'University of Canterbury',
        coordinates: [-43.5232, 172.5835],
        location: 'Christchurch, New Zealand',
        year: '2024-2025',
        link: 'https://www.canterbury.ac.nz',
        img: '/education/uc-ds-all.jpg',
    },
    {
        type: 'education',
        name: 'Bachelor of Information Technology',
        client: 'Otago Polytechnic',
        coordinates: [-45.8664633, 170.5182829],
        location: 'Dunedin, New Zealand',
        year: '2017-2021',
        link: 'https://www.op.ac.nz',
        img: '/education/awared-best-programmer.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Changpingli · 常平里',
        coordinates: [26.564722, 104.858717],
        location: 'Liupanshui, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/changpingli.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Dalincheng · 大林城',
        coordinates: [25.725958, 104.449007],
        location: 'Liupanshui, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/dalincheng.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Fenghuangjiayuan · 凤凰嘉苑',
        coordinates: [30.2788597, 109.4846285],
        location: 'Enshi, Hubei, China',
        year: '2020-2021',
        link: '',
        img: '/vr/fhjy.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Number 1 Parking · 公园①号',
        coordinates: [27.326395, 105.280762],
        location: 'Bijie, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/gyyh.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Hengtianfengxijun · 恒天枫溪郡',
        coordinates: [39.163164, 116.354244],
        location: 'Langfang, Hebei, China',
        year: '2020-2021',
        link: '',
        img: '/vr/htfxj.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Jiahe Garden in Sky · 家和空中花园',
        coordinates: [29.475417, 109.406526],
        location: 'Enshi, Hubei, China',
        year: '2020-2021',
        link: '',
        img: '/vr/jhhy.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Jinnanwan · 金澜湾',
        coordinates: [27.502244, 106.234353],
        location: 'Bijie, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/jlw.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Jiangnanyipin · 江南一品',
        coordinates: [27.754975, 107.461993],
        location: 'Zunyi, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/jnyp.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Jiangxiangmingmen · 将相名门',
        coordinates: [28.175622, 109.185229],
        location: 'Tongren, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/jxmm.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Jinsha · 金沙将相名门',
        coordinates: [27.497812, 106.233872],
        location: 'Jinsha, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/jsjxmm.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Guiyuan · 盘州府壹号',
        coordinates: [25.692363, 104.485536],
        location: 'Liupanshui, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/pzf.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Taifu Wutongxi · 泰府梧桐栖',
        coordinates: [36.568705, 111.742927],
        location: 'Huozhou, Shanxi, China',
        year: '2020-2021',
        link: '',
        img: '/vr/tf.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Yuheyuan · 通盛御河园',
        coordinates: [28.309843, 106.225531],
        location: 'Zaozhuang, Shandong, China',
        year: '2020-2021',
        link: '',
        img: '/vr/tsyhy.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Yuheyuan · 文璟上府',
        coordinates: [26.24033, 109.140568],
        location: 'Liping, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/wjsf.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Dongsheng - 芯宸时代',
        coordinates: [29.681751, 109.162283],
        location: 'Enshi，Hubei, China',
        year: '2020-2021',
        link: '',
        img: '/vr/xcsd.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Lvcheng · 迎宾华府',
        coordinates: [39.122386, 116.415274],
        location: 'Langfang, Hebei, China',
        year: '2020-2021',
        link: '',
        img: '/vr/ybhf.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Jiahe · 雲尚星城',
        coordinates: [29.688752, 109.149443],
        location: 'Enshi, Hubei, China',
        year: '2020-2021',
        link: '',
        img: '/vr/ysxc.jpg',
    },
    {
        type: 'project',
        name: 'Interactive 360° Virtual Tour Application',
        client: 'Yuecheng · 悦城',
        coordinates: [27.579996, 106.864341],
        location: 'Zunyi, Guizhou, China',
        year: '2020-2021',
        link: '',
        img: '/vr/zyyc.jpg',
    },
    {
        type: 'project',
        name: 'Tenglong Cave',
        client: '腾龙洞',
        coordinates: [30.3335111, 108.98434],
        location: 'Lichuan, Hubei, China',
        year: '2019',
        link: 'http://tenglongdong.net.cn/',
        img: '/website/tenglongdong.jpg',
    },
    {
        type: 'project',
        name: 'Badong Tourism Bureau',
        client: '巴东县旅游局',
        coordinates: [31.0419753, 110.3386598],
        location: 'Badong, Hubei, China',
        year: '2019',
        link: '',
        img: '',
    },
    {
        type: 'project',
        name: 'Jinguo Tea',
        client: '金果茶叶',
        coordinates: [30.2889132, 110.2148372],
        location: 'Badong, Hubei, China',
        year: '2019',
        link: '',
        img: '',
    },
    {
        type: 'project',
        name: 'Enshi Central Hospital',
        client: '恩施州中心医院',
        coordinates: [30.297884, 109.4955927],
        location: 'Enshi, Hubei, China',
        year: '2019',
        link: 'https://www.es9e.cn/',
        img: '/website/es9e.jpg',
    },
    {
        type: 'project',
        name: 'FitsGo',
        client: 'Mobile App',
        coordinates: [-45.8750186, 170.4973482],
        location: 'Dunedin, New Zealand',
        year: '2019',
        link: 'https://github.com/aemooooon/FitsGo',
        img: '/fitsgo/fitsgo.02.jpg',
    },
    {
        type: 'project',
        name: 'Travel Assistant',
        client: 'Mobile App',
        coordinates: [-45.8710403, 170.4855276],
        location: 'Dunedin, New Zealand',
        year: '2019',
        link: 'https://github.com/aemooooon/travel-assistant',
        img: '/travelassistant/ta02.jpg',
    },
    {
        type: 'project',
        name: 'ECAN Data Pipeline',
        client: 'University of Canterbury',
        coordinates: [-43.5357406, 172.6358119],
        location: 'Christchurch, New Zealand',
        year: '2024',
        link: 'https://github.com/aemooooon/DATA472-Individual-Project-Submission',
        img: '/data472/v1.gif',
    },
    {
        type: 'activity',
        name: 'CITANZ CHCH Events',
        client: 'Chinese IT Association New Zealand',
        coordinates: [-43.5828903, 172.5695089],
        location: 'Halswell Library, Christchurch',
        year: '2024-2025',
        link: 'https://www.cita.org.nz/',
        img: '/citanz/cita-04.5.jpg',
    },
    {
        type: 'activity',
        name: 'Save Kiwi',
        client: 'AI Hackathon 2024',
        coordinates: [-43.5218726, 172.5674936],
        location: 'University of Canterbury',
        year: '2024',
        link: 'https://www.cita.org.nz/',
        img: '/f4/f4.jpg',
    },
];
