// ========================================================================================
// 画廊数据配置 - 包含3D画廊展示内容
// ========================================================================================

export const galleryData = [
    // 灯箱位置 (Special Lightbox Position)
    {
        id: 'gallery_lightbox',
        type: 'image',
        src: '/gallery/gallery-vertical-0.jpg',
        thumbnail: '/gallery/gallery-vertical-0.jpg',
        dimensions: { width: 800, height: 1200 }, // 预计算尺寸
        aspectRatio: 0.67, // 预计算宽高比 (竖版)
        title: {
            en: 'Featured Showcase',
            zh: '精选展示',
        },
        description: {
            en: 'Special lightbox display piece',
            zh: '特殊灯箱展示作品',
        },
        date: '2025-08-22',
        tags: ['lightbox', 'featured', 'special'],
        orientation: 'vertical',
        position: 'lightbox',
        wall: 'lightbox',
    },
    // 竖向墙展示 (32米墙，5张图片)
    {
        id: 'gallery_vertical_1',
        type: 'image',
        src: '/gallery/gallery-vertical-1.jpg',
        thumbnail: '/gallery/gallery-vertical-1.jpg',
        dimensions: { width: 800, height: 1200 }, // 预计算尺寸
        aspectRatio: 0.67, // 预计算宽高比 (竖版)
        title: {
            en: 'Portrait Excellence',
            zh: '肖像卓越',
        },
        description: {
            en: 'Professional portrait photography excellence',
            zh: '专业肖像摄影卓越表现',
        },
        date: '2025-08-22',
        tags: ['portrait', 'excellence', 'professional'],
        orientation: 'vertical',
        position: 'wall',
        wall: 'vertical_wall_32m',
    },
    {
        id: 'gallery_vertical_2_video',
        type: 'video',
        src: '/cube-textures/home.mp4',
        thumbnail: '/cube-textures/home.mp4', // 视频文件作为缩略图
        title: {
            en: 'Home Vision',
            zh: '家园视界',
        },
        description: {
            en: 'Interactive home environment visualization',
            zh: '交互式家园环境可视化',
        },
        date: '2025-08-22',
        tags: ['video', 'home', 'interactive'],
        orientation: 'vertical',
        position: 'wall',
        wall: 'vertical_wall_32m',
        // 视频特定配置
        autoplay: true,
        loop: true,
        muted: true, // 默认静音以符合浏览器政策
        controls: false, // 在画廊中不显示控制器
    },
    {
        id: 'gallery_vertical_3',
        type: 'image',
        src: '/gallery/gallery-vertical-3.jpg',
        thumbnail: '/gallery/gallery-vertical-3.jpg',
        dimensions: { width: 800, height: 1200 }, // 预计算尺寸
        aspectRatio: 0.67, // 预计算宽高比 (竖版)
        title: {
            en: 'Visual Harmony',
            zh: '视觉和谐',
        },
        description: {
            en: 'Perfect visual harmony in composition',
            zh: '构图中的完美视觉和谐',
        },
        date: '2025-08-22',
        tags: ['visual', 'harmony', 'composition'],
        orientation: 'vertical',
        position: 'wall',
        wall: 'vertical_wall_32m',
    },
    {
        id: 'gallery_vertical_4',
        type: 'image',
        src: '/gallery/gallery-vertical-4.jpg',
        thumbnail: '/gallery/gallery-vertical-4.jpg',
        title: {
            en: 'Creative Expression',
            zh: '创意表达',
        },
        description: {
            en: 'Innovative creative expression in digital art',
            zh: '数字艺术中的创新创意表达',
        },
        date: '2025-08-22',
        tags: ['creative', 'expression', 'digital'],
        orientation: 'vertical',
        position: 'wall',
        wall: 'vertical_wall_32m',
    },
    {
        id: 'gallery_vertical_5',
        type: 'image',
        src: '/gallery/gallery-vertical-5.jpg',
        thumbnail: '/gallery/gallery-vertical-5.jpg',
        title: {
            en: 'Modern Aesthetics',
            zh: '现代美学',
        },
        description: {
            en: 'Modern aesthetic principles demonstration',
            zh: '现代美学原理演示',
        },
        date: '2025-08-22',
        tags: ['modern', 'aesthetics', 'principles'],
        orientation: 'vertical',
        position: 'wall',
        wall: 'vertical_wall_32m',
    },
    // 横向墙展示 (64米墙，16张图片，可能上下2层)
    {
        id: 'gallery_horizontal_1',
        type: 'image',
        src: '/gallery/gallery-horizontal-1.jpg',
        thumbnail: '/gallery/gallery-horizontal-1.jpg',
        dimensions: { width: 1600, height: 900 }, // 预计算尺寸
        aspectRatio: 1.78, // 预计算宽高比 (横版 16:9)
        title: {
            en: 'Landscape Panorama 1',
            zh: '全景风光 1',
        },
        description: {
            en: 'Wide panoramic view capturing natural beauty',
            zh: '捕捉自然美景的宽幅全景视图',
        },
        date: '2025-08-22',
        tags: ['landscape', 'panorama', 'nature'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 1, y: 1 },
    },
    {
        id: 'gallery_horizontal_2',
        type: 'image',
        src: '/gallery/gallery-horizontal-2.jpg',
        thumbnail: '/gallery/gallery-horizontal-2.jpg',
        dimensions: { width: 1600, height: 900 }, // 预计算尺寸
        aspectRatio: 1.78, // 预计算宽高比 (横版 16:9)
        title: {
            en: 'Landscape Panorama 2',
            zh: '全景风光 2',
        },
        description: {
            en: 'Contemporary artistic vision exploration',
            zh: '当代艺术视野探索',
        },
        date: '2025-08-22',
        tags: ['artistic', 'vision', 'contemporary'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 2, y: 1 },
    },
    {
        id: 'gallery_horizontal_3',
        type: 'image',
        src: '/gallery/gallery-horizontal-3.jpg',
        thumbnail: '/gallery/gallery-horizontal-3.jpg',
        title: {
            en: 'Visual Harmony',
            zh: '视觉和谐',
        },
        description: {
            en: 'Perfect visual harmony in composition',
            zh: '构图中的完美视觉和谐',
        },
        date: '2025-08-22',
        tags: ['visual', 'harmony', 'composition'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 3, y: 1 },
    },
    {
        id: 'gallery_horizontal_4',
        type: 'image',
        src: '/gallery/gallery-horizontal-4.jpg',
        thumbnail: '/gallery/gallery-horizontal-4.jpg',
        title: {
            en: 'Creative Expression',
            zh: '创意表达',
        },
        description: {
            en: 'Innovative creative expression in digital art',
            zh: '数字艺术中的创新创意表达',
        },
        date: '2025-08-22',
        tags: ['creative', 'expression', 'digital'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 4, y: 1 },
    },
    {
        id: 'gallery_horizontal_5',
        type: 'image',
        src: '/gallery/gallery-horizontal-5.jpg',
        thumbnail: '/gallery/gallery-horizontal-5.jpg',
        title: {
            en: 'Modern Aesthetics',
            zh: '现代美学',
        },
        description: {
            en: 'Modern aesthetic principles demonstration',
            zh: '现代美学原理演示',
        },
        date: '2025-08-22',
        tags: ['modern', 'aesthetics', 'principles'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 5, y: 1 },
    },
    {
        id: 'gallery_horizontal_6',
        type: 'image',
        src: '/gallery/gallery-horizontal-6.jpg',
        thumbnail: '/gallery/gallery-horizontal-6.jpg',
        title: {
            en: 'Dynamic Flow',
            zh: '动态流动',
        },
        description: {
            en: 'Capture of dynamic flow in natural movement',
            zh: '捕捉自然运动中的动态流动',
        },
        date: '2025-08-22',
        tags: ['dynamic', 'flow', 'movement'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 6, y: 1 },
    },
    {
        id: 'gallery_horizontal_7',
        type: 'image',
        src: '/gallery/gallery-horizontal-7.jpg',
        thumbnail: '/gallery/gallery-horizontal-7.jpg',
        title: {
            en: 'Color Symphony',
            zh: '色彩交响',
        },
        description: {
            en: 'Rich color palette symphony in visual art',
            zh: '视觉艺术中的丰富色彩调色板交响乐',
        },
        date: '2025-08-22',
        tags: ['color', 'symphony', 'palette'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 7, y: 1 },
    },
    {
        id: 'gallery_horizontal_8',
        type: 'image',
        src: '/gallery/gallery-horizontal-8.jpg',
        thumbnail: '/gallery/gallery-horizontal-8.jpg',
        title: {
            en: 'Textural Details',
            zh: '纹理细节',
        },
        description: {
            en: 'Intricate textural details in close-up photography',
            zh: '特写摄影中的复杂纹理细节',
        },
        date: '2025-08-22',
        tags: ['texture', 'details', 'closeup'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'upper',
        gridPosition: { x: 8, y: 1 },
    },
    // 下层横向展示
    {
        id: 'gallery_horizontal_9',
        type: 'image',
        src: '/gallery/gallery-horizontal-9.jpg',
        thumbnail: '/gallery/gallery-horizontal-9.jpg',
        title: {
            en: 'Geometric Patterns',
            zh: '几何图案',
        },
        description: {
            en: 'Sophisticated geometric patterns in architectural design',
            zh: '建筑设计中的精致几何图案',
        },
        date: '2025-08-22',
        tags: ['geometric', 'patterns', 'architecture'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 1, y: 2 },
    },
    {
        id: 'gallery_horizontal_10',
        type: 'image',
        src: '/gallery/gallery-horizontal-10.jpg',
        thumbnail: '/gallery/gallery-horizontal-10.jpg',
        title: {
            en: 'Natural Elements',
            zh: '自然元素',
        },
        description: {
            en: 'Pure natural elements in environmental photography',
            zh: '环境摄影中的纯净自然元素',
        },
        date: '2025-08-22',
        tags: ['natural', 'elements', 'environment'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 2, y: 2 },
    },
    {
        id: 'gallery_horizontal_11',
        type: 'image',
        src: '/gallery/gallery-horizontal-11.jpg',
        thumbnail: '/gallery/gallery-horizontal-11.jpg',
        title: {
            en: 'Light Studies',
            zh: '光影研究',
        },
        description: {
            en: 'Detailed studies of light and shadow interplay',
            zh: '光影相互作用的详细研究',
        },
        date: '2025-08-22',
        tags: ['light', 'shadow', 'studies'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 3, y: 2 },
    },
    {
        id: 'gallery_horizontal_12',
        type: 'image',
        src: '/gallery/gallery-horizontal-12.jpg',
        thumbnail: '/gallery/gallery-horizontal-12.jpg',
        title: {
            en: 'Abstract Concepts',
            zh: '抽象概念',
        },
        description: {
            en: 'Exploration of abstract concepts through visual metaphors',
            zh: '通过视觉隐喻探索抽象概念',
        },
        date: '2025-08-22',
        tags: ['abstract', 'concepts', 'metaphors'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 4, y: 2 },
    },
    {
        id: 'gallery_horizontal_13',
        type: 'image',
        src: '/gallery/gallery-horizontal-13.jpg',
        thumbnail: '/gallery/gallery-horizontal-13.jpg',
        title: {
            en: 'Emotional Depth',
            zh: '情感深度',
        },
        description: {
            en: 'Capturing emotional depth in human portraiture',
            zh: '在人物肖像中捕捉情感深度',
        },
        date: '2025-08-22',
        tags: ['emotional', 'depth', 'portraiture'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 5, y: 2 },
    },
    {
        id: 'gallery_horizontal_14',
        type: 'image',
        src: '/gallery/gallery-horizontal-14.jpg',
        thumbnail: '/gallery/gallery-horizontal-14.jpg',
        title: {
            en: 'Cultural Heritage',
            zh: '文化遗产',
        },
        description: {
            en: 'Documentation of cultural heritage and traditions',
            zh: '文化遗产和传统的记录',
        },
        date: '2025-08-22',
        tags: ['cultural', 'heritage', 'traditions'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 6, y: 2 },
    },
    {
        id: 'gallery_horizontal_15',
        type: 'image',
        src: '/gallery/gallery-horizontal-15.jpg',
        thumbnail: '/gallery/gallery-horizontal-15.jpg',
        title: {
            en: 'Urban Landscapes',
            zh: '城市景观',
        },
        description: {
            en: 'Contemporary urban landscapes and cityscapes',
            zh: '当代城市景观和城市风光',
        },
        date: '2025-08-22',
        tags: ['urban', 'landscapes', 'cityscapes'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 7, y: 2 },
    },
    {
        id: 'gallery_horizontal_16',
        type: 'image',
        src: '/gallery/gallery-horizontal-16.jpg',
        thumbnail: '/gallery/gallery-horizontal-16.jpg',
        title: {
            en: 'Future Visions',
            zh: '未来愿景',
        },
        description: {
            en: 'Conceptual visions of future possibilities',
            zh: '未来可能性的概念愿景',
        },
        date: '2025-08-22',
        tags: ['future', 'visions', 'conceptual'],
        orientation: 'horizontal',
        position: 'wall',
        wall: 'horizontal_wall_64m',
        layer: 'lower',
        gridPosition: { x: 8, y: 2 },
    },
];
