// ========================================================================================
// 项目数据配置 - 包含国际化项目信息
// ========================================================================================

export const projectsData = [
    {
        type: {
            en: 'Front End',
            zh: '前端开发',
        },
        title: {
            en: 'Front End Developer',
            zh: '前端开发工程师',
        },
        name: {
            en: 'Corridor of Light and Shadow',
            zh: '浮生长廊',
        },
        company: 'Hua Wang',
        description: {
            en: [
                'As I actively pursue web development opportunities and prepare for technical interviews, I created this personal portfolio to dynamically showcase my skills and demonstrate my expertise in modern web development. This immersive digital experience serves as a living testament to my capabilities, presenting both my professional journey and technical mastery through interactive storytelling and cutting-edge implementation.',
                'The application leverages React 18 with modern hooks architecture, utilizing useState, useEffect, useCallback, and useMemo for efficient state management and component optimization. Vite serves as the build tool with custom configuration for ES modules, tree-shaking, and optimized chunk splitting. Advanced state management is implemented through Zustand with persistence middleware, featuring centralized store patterns, reactive state updates, and immutable state transformations for predictable data flow. Comprehensive internationalization (i18n) system supports English and Chinese with dynamic language switching, persistent user preferences, and culturally appropriate content adaptation.',
                'The standout feature is an immersive 3D animated cube opening sequence powered by GSAP timeline animations and Three.js WebGL rendering. Advanced WebGL performance optimization includes geometry instancing, texture atlasing, and efficient memory management to maintain 60fps across devices. Multiple dynamic themes are supported through a sophisticated CSS custom properties system with runtime switching, CSS-in-JS integration, and blend mode effects for visual harmony.',
                'Complex SPA architecture employs custom routing logic with section-based navigation, implementing smooth scrolling algorithms with intersection observers and momentum-based transitions. Advanced scroll management includes scroll hijacking, directional detection, and synchronized animation systems. The intelligent cursor system features context-aware hover effects, directional tracking, and smooth interpolation between interaction states using custom mouse tracking algorithms. Comprehensive responsive design ensures optimal user experience across desktop, tablet, and mobile devices with fluid layouts, adaptive typography scaling, and touch-optimized interactions.',
                'Performance optimization includes strategic code splitting with React.lazy and dynamic imports, WebGL resource pooling, texture compression, and efficient animation frame management. The application implements comprehensive error boundaries, progressive enhancement patterns, and accessibility features including ARIA labels, keyboard navigation support, and semantic HTML structure. Advanced CSS techniques include mix-blend-mode compositions, backdrop-filter effects, and GPU-accelerated animations.',
                'The project showcases modern development workflows including ESLint and Prettier integration, component-driven development with atomic design principles, and comprehensive DevOps practices. Automated CI/CD pipeline is implemented through GitHub Actions, featuring automated testing, code quality checks, and seamless deployment to GitHub Pages with zero-downtime releases. The architecture demonstrates clean separation of concerns with custom hooks abstraction, utility-first CSS methodology, and maintainable code patterns suitable for enterprise-scale applications.',
            ],
            zh: [
                '在我积极寻找web开发机会并为技术面试做准备的过程中，我创建了这个个人作品集来动态展示我的技能，并展现我在现代web开发方面的专业能力。这个沉浸式数字体验作为我能力的生动证明，通过交互式叙述和前沿技术实现，展现了我的职业历程和技术精通。',
                '应用程序采用React 18现代hooks架构，利用useState、useEffect、useCallback和useMemo实现高效的状态管理和组件优化。Vite作为构建工具，配置了ES模块、树摇优化和优化的代码块分割。高级状态管理通过Zustand持久化中间件实现，具有集中式存储模式、响应式状态更新和不可变状态转换，确保可预测的数据流。全面的国际化(i18n)系统支持中英文动态语言切换、持久化用户偏好和文化适应性内容调整。',
                '突出特色是由GSAP时间轴动画和Three.js WebGL渲染驱动的沉浸式3D立方体开场序列。先进的WebGL性能优化包括几何体实例化、纹理图集和高效内存管理，在各种设备上保持60fps。通过复杂的CSS自定义属性系统支持多种动态主题，具有运行时切换、CSS-in-JS集成和用于视觉和谐的混合模式效果。',
                '复杂的SPA架构采用基于章节导航的自定义路由逻辑，实现带有交叉观察器和基于动量转换的平滑滚动算法。高级滚动管理包括滚动劫持、方向检测和同步动画系统。智能光标系统具有上下文感知的悬停效果、方向跟踪，以及使用自定义鼠标跟踪算法在交互状态间的平滑插值。全面的响应式设计确保在桌面、平板和移动设备上的最佳用户体验，具有流式布局、自适应字体缩放和触控优化交互。',
                '性能优化包括使用React.lazy和动态导入的策略性代码分割、WebGL资源池、纹理压缩和高效的动画帧管理。应用程序实现了全面的错误边界、渐进增强模式和无障碍功能，包括ARIA标签、键盘导航支持和语义HTML结构。高级CSS技术包括混合模式合成、背景滤镜效果和GPU加速动画。',
                '项目展示了现代开发工作流程，包括ESLint和Prettier集成、基于原子设计原则的组件驱动开发和全面的DevOps实践。通过GitHub Actions实现自动化CI/CD流水线，具有自动化测试、代码质量检查和零停机部署到GitHub Pages的无缝发布。架构展示了关注点的清晰分离，具有自定义hooks抽象、实用优先的CSS方法论和适合企业级应用程序的可维护代码模式。',
            ],
        },
        coordinates: [-43.5224316, 172.5943064],
        location: 'Christchurch, New Zealand',
        year: '2025',
        links: {
            live: 'https://www.hua.nz/',
            github: 'https://github.com/aemooooon/hua.nz',
        },
        img: [
            '/hua.nz/hua.nz.1.jpg',
            '/hua.nz/hua.nz.2.jpg',
            '/hua.nz/hua.nz.3.jpg',
            '/hua.nz/hua.nz.4.jpg',
            '/hua.nz/hua.nz.5.jpg',
            '/hua.nz/hua.nz.6.jpg',
            '/hua.nz/hua.nz.7.jpg',
            '/hua.nz/hua.nz.8.jpg',
            '/hua.nz/hua.nz.9.jpg',
            '/hua.nz/hua.nz.10.jpg',
            '/hua.nz/hua.nz.11.jpg',
            '/hua.nz/hua.nz.12.jpg',
            '/hua.nz/hua.nz.13.jpg',
            '/hua.nz/hua.nz.14.jpg',
            '/hua.nz/hua.nz.15.jpg',
            '/hua.nz/hua.nz.16.jpg',
            '/hua.nz/hua.nz.17.jpg',
        ],
    },
    {
        type: {
            en: 'Full Stack',
            zh: '全栈开发',
        },
        title: {
            en: 'Full Stack Developer',
            zh: '全栈开发工程师',
        },
        name: {
            en: 'Orchard Sampling Scheduler',
            zh: '果园采样调度系统',
        },
        company: 'Zespri International',
        description: {
            en: [
                'This project involved the end-to-end design and implementation of an orchard sampling optimization platform for Zespri International, New Zealand’s leading kiwifruit company. The primary goal was to create a system capable of scheduling and optimizing sampling tasks for hundreds of orchards across the Bay of Plenty region, while addressing challenges of time constraints, geographic distribution, and efficiency in field operations.',
                'From a technical standpoint, the system was designed with a modern full-stack architecture. The frontend was built with React and TailwindCSS, providing a responsive, intuitive interface for managers to interact with orchard data and adjust schedules dynamically. For mapping and geospatial visualization, Leaflet and Folium were integrated to enable interactive exploration of orchard locations and routes, while OpenRouteService (with a locally deployed instance) powered multi-waypoint route optimization.',
                'The backend was developed using Flask, exposing RESTful APIs to handle data processing, business logic, and communication with the frontend. A lightweight SQLite database was chosen to ensure portability and offline usability, enabling the system to function even in rural areas with limited connectivity. ETL pipelines were developed in Python to process diverse agricultural datasets, including orchard GPS coordinates, sampling windows, and priority rules. These pipelines automated the transformation of raw datasets into optimized scheduling inputs.',
                'At the algorithmic level, the project tackled a variant of the Travelling Salesman Problem (TSP). Pre-computed pairwise distance matrices (generated via OpenRouteService) served as the foundation for optimization. Multiple TSP algorithms were evaluated for their balance of efficiency, scalability, and explainability, ensuring that the methodology could be communicated clearly to both technical and non-technical stakeholders. This data-driven approach was critical, given the project’s research orientation as part of a Master of Applied Data Science.',
                'The system incorporated best practices not only in code but also in process. Agile-inspired iteration cycles guided development, with regular feedback loops from the client to validate usability and responsiveness. CI/CD pipelines were configured via GitHub Actions to automate deployment to an Azure VM, ensuring a reliable and reproducible release process. Containerization with Docker was used for environment consistency, while Nginx was deployed as a reverse proxy for secure hosting.',
                'Beyond technical implementation, the project emphasized architectural clarity and trade-off analysis. Decisions such as choosing SQLite over heavier databases, deploying OpenRouteService locally for offline reliability, and designing an interface tailored to field managers’ workflows all reflected a thoughtful, context-driven approach. The result was not only a functional product but also a research contribution, demonstrating how data science and software engineering can be combined to address real-world agricultural challenges.',
                'Ultimately, the Orchard Sampling Scheduler improved efficiency by enabling intelligent workload allocation, minimizing travel times, and aligning sampling tasks with operational constraints. It stands as both a professional-grade software system and a demonstration of applying algorithms, geospatial analysis, and system design principles to practical, industry-scale problems.',
            ],
            zh: [
                '本项目是为新西兰领先的奇异果企业佳沛（Zespri International）设计与实现的一套果园采样优化平台，旨在解决丰盛湾地区数百个果园的采样调度问题。系统的核心目标是应对时间窗口、地理分布与作业效率等多重挑战，在保障果实品质评估的同时提高整体采样效率。',
                '在技术架构上，平台采用现代全栈方案构建。前端基于 React 与 TailwindCSS，实现了响应式、直观的交互界面，便于管理人员实时查看果园数据与动态调整任务。地图与地理可视化方面，系统集成了 Leaflet 与 Folium，以支持果园分布与路线的交互式展示，同时结合本地部署的 OpenRouteService 实现多点路径优化。',
                '后端采用 Flask 构建 RESTful API，负责数据处理、业务逻辑与前端交互。数据库选择轻量级 SQLite，以确保系统的可移植性与离线可用性，适用于乡村地区的弱网环境。Python 编写的 ETL 数据管道用于处理多样化的农业数据集，包括果园坐标、采样时间窗口与优先级规则，实现了从原始数据到优化调度输入的全自动转换。',
                '在算法层面，项目研究并实现了旅行商问题 (TSP) 的变体。通过 OpenRouteService 预计算的两两距离矩阵作为优化基础，比较并选取了多种 TSP 算法，以平衡效率、可扩展性与可解释性，确保方法论既科学可靠又便于行业用户理解。作为应用数据科学硕士的研究性项目，这种数据驱动的思路尤为关键。',
                '项目在代码与过程上都注重最佳实践。开发过程采用敏捷式迭代，与客户保持定期反馈循环，以确保系统的易用性与实际契合度。CI/CD 管道基于 GitHub Actions 构建，自动化部署至 Azure VM，实现了稳定可重复的上线流程。Docker 容器化确保了环境一致性，Nginx 则作为反向代理提供安全的服务托管。',
                '除技术实现外，本项目还强调架构清晰度与取舍分析。例如：选择 SQLite 而非重量级数据库以提升便携性，在本地部署 OpenRouteService 保证离线可用性，以及针对田间管理者需求定制交互界面，这些都体现了以场景为导向的工程判断。成果不仅是一套可投入使用的系统，更是一份研究探索，展现了数据科学与软件工程结合解决农业行业实际问题的可能性。',
                '最终，该果园采样调度平台通过智能化任务分配、出行时间最小化和调度自动化，使采样效率显著提升。它既是一款专业级的软件系统，也是一份将算法、地理空间分析与系统设计应用于产业实践的案例。',
            ],
        },
        coordinates: [-37.7866, 176.4416],
        location: 'Bay of Plenty, New Zealand',
        year: '2024-2025',
        links: {
            official: 'https://www.zespri.com',
        },
        img: [
            '/zespri/zespri-ors.jpg',
            '/zespri/zespri_poster.png',
            '/zespri/zespri.1.jpg',
            '/zespri/zespri.2.jpg',
        ],
    },
    {
        type: {
            en: 'Front End',
            zh: '前端开发',
        },
        title: {
            en: 'Front End Developer',
            zh: '前端开发工程师',
        },
        name: {
            en: 'Realibox Portal',
            zh: '引力波官方门户',
        },
        company: 'Realibox',
        description: {
            en: [
                "As a Senior Frontend Developer at Realibox, I led the development of the official website and marketing portal for a cutting-edge 3D cloud collaboration platform. This enterprise-level project showcased advanced frontend architecture and served as the primary marketing gateway for Realibox's comprehensive 3D design ecosystem, targeting professional designers, architects, and enterprise clients across multiple industries.",
                'The application was built with Next.js 12 featuring server-side rendering (SSR) for optimal SEO performance and lightning-fast page loads. Implemented sophisticated device detection and adaptive rendering, providing separate optimized experiences for desktop and mobile clients through dynamic component loading. Advanced state management was achieved using MobX with reactive patterns, enabling real-time UI updates and efficient cross-component data synchronization across complex user workflows.',
                'Architected a sophisticated multi-theme CSS system using CSS modules, LESS preprocessor, and runtime theme switching capabilities. Implemented advanced responsive design patterns supporting seamless transitions between desktop and mobile layouts with fluid typography scaling, touch-optimized interactions, and adaptive navigation structures. The design system featured custom CSS blend modes, GPU-accelerated animations, and sophisticated visual effects that enhanced user engagement while maintaining optimal performance.',
                'Complex single-page application (SPA) architecture employed custom routing logic with smooth section-based navigation, implementing intersection observers for scroll-triggered animations and dynamic content loading. Advanced scroll management included momentum-based transitions, directional detection, and synchronized animation sequences that created an immersive storytelling experience. Integrated Swiper.js for touch-enabled carousels and interactive content presentation.',
                'Performance optimization strategies included strategic code splitting with dynamic imports, image optimization supporting WebP and modern formats, lazy loading implementations, and efficient bundle management. Implemented comprehensive error boundaries, progressive loading states, and robust exception handling. Advanced DevOps practices included GitLab CI/CD pipeline automation with multi-environment deployments, automated testing workflows, and zero-downtime production releases.',
                'The project demonstrated enterprise-scale frontend development capabilities including component-driven architecture with atomic design principles, comprehensive TypeScript integration, and maintainable code patterns suitable for large development teams. Collaborated extensively with UX/UI designers, product managers, and backend engineers in an Agile environment, ensuring pixel-perfect implementation and seamless API integration for dynamic content management.',
            ],
            zh: [
                '作为Realibox的高级前端开发工程师，我主导开发了前沿3D云协作平台的官方网站和营销门户。这个企业级项目展示了先进的前端架构，作为Realibox综合3D设计生态系统的主要营销门户，面向多个行业的专业设计师、建筑师和企业客户。',
                '应用程序使用Next.js 12构建，具有服务器端渲染(SSR)功能，实现最佳SEO性能和闪电般的页面加载速度。实现了复杂的设备检测和自适应渲染，通过动态组件加载为桌面和移动客户端提供单独优化的体验。使用MobX的响应式模式实现高级状态管理，在复杂用户工作流程中实现实时UI更新和高效的跨组件数据同步。',
                '架构了复杂的多主题CSS系统，使用CSS模块、LESS预处理器和运行时主题切换功能。实现了先进的响应式设计模式，支持桌面和移动布局之间的无缝转换，具有流式字体缩放、触控优化交互和自适应导航结构。设计系统具有自定义CSS混合模式、GPU加速动画和复杂视觉效果，在保持最佳性能的同时增强用户参与度。',
                '复杂的单页应用程序(SPA)架构采用自定义路由逻辑和平滑的基于章节的导航，实现交叉观察器进行滚动触发动画和动态内容加载。高级滚动管理包括基于动量的转换、方向检测和同步动画序列，创造沉浸式叙述体验。集成Swiper.js实现触控轮播和交互式内容展示。',
                '性能优化策略包括使用动态导入的策略性代码分割、支持WebP和现代格式的图像优化、懒加载实现和高效的包管理。实现了全面的错误边界、渐进加载状态和健壮的异常处理。先进的DevOps实践包括GitLab CI/CD流水线自动化、多环境部署、自动化测试工作流程和零停机生产发布。',
                '项目展示了企业级前端开发能力，包括基于原子设计原则的组件驱动架构、全面的TypeScript集成，以及适合大型开发团队的可维护代码模式。在敏捷环境中与UX/UI设计师、产品经理和后端工程师广泛协作，确保像素完美的实现和动态内容管理的无缝API集成。',
            ],
        },
        coordinates: [22.9951158, 113.3335372],
        location: 'Guangzhou, China',
        year: '2021-2023',
        links: {
            live: 'https://www.realibox.com/',
        },
        img: [
            '/realibox/official/official.01.jpg',
            '/realibox/official/official.02.jpg',
            '/realibox/official/official.03.jpg',
        ],
    },
    {
        type: {
            en: 'Front End',
            zh: '前端开发',
        },
        title: {
            en: 'Front End Developer',
            zh: '前端开发工程师',
        },
        name: {
            en: 'Realibox Hub & 3D Editor',
            zh: '引力波3D编辑器',
        },
        company: 'Realibox',
        description: {
            en: [
                'As a Senior Frontend Developer at Realibox, I architected and developed a comprehensive cloud-based 3D design platform comprising five interconnected microservice repositories. This sophisticated system provided professional designers and enterprises with advanced 3D modeling, rendering, and collaboration capabilities through a modular, scalable architecture that demonstrated mastery of modern web development and distributed system design.',
                'The platform was built using cutting-edge technologies including React 18, Vite as the build tool for lightning-fast development experience, and MobX 6 for reactive state management across complex application workflows. Implemented comprehensive TypeScript integration throughout all microservices, ensuring type safety and maintainable code architecture. The system utilized advanced WebGL-based 3D rendering engines with custom canvas implementations for real-time 3D scene manipulation and high-performance visualization.',
                'Architected a sophisticated microservice ecosystem with five specialized repositories: designhub-accounts-web for user authentication and account management, designhub-common-core containing shared utilities and business logic, designhub-common-ui housing reusable UI components, designhub-hub-web serving as the main platform dashboard, and ishot-editor-web providing the core 3D editing capabilities. Each service was designed with clear separation of concerns and robust API integrations.',
                'The core 3D editor featured advanced WebGL rendering capabilities with real-time scene manipulation, material editing systems, collaborative editing features, and cloud-based project synchronization. Implemented sophisticated state management using MobX stores for editor, scene, render, material, and user management. The system supported complex 3D workflows including model importing, texture management, lighting control, and high-quality rendering pipelines with performance optimization for handling large 3D assets.',
                'Implemented comprehensive DevOps practices including automated CI/CD pipelines using GitLab, multi-environment deployment strategies, and advanced package management with pnpm workspaces and Turbo for efficient monorepo operations. Utilized Changesets for version management and automated npm package publishing to private registries. The system featured robust error handling, comprehensive testing with Vitest and Cypress, and progressive loading strategies for optimal user experience.',
                'The project demonstrated enterprise-scale frontend development capabilities including component-driven architecture with atomic design principles, advanced internationalization support, theme management systems, and accessibility features. Collaborated extensively with backend engineers, 3D graphics specialists, and product teams in an Agile environment, ensuring seamless integration of complex 3D workflows with intuitive user interfaces and robust cloud infrastructure.',
            ],
            zh: [
                '作为Realibox的高级前端开发工程师，我参与架构并开发了一个全面的云端3D设计平台，包含五个相互连接的微服务代码库。这个复杂的系统为专业设计师和企业提供了先进的3D建模、渲染和协作功能，通过模块化、可扩展的架构展示了现代web开发和分布式系统设计的精通。',
                '平台采用前沿技术构建，包括React 18、Vite作为构建工具提供闪电般的开发体验，以及MobX 6用于复杂应用程序工作流程的响应式状态管理。在所有微服务中实现了全面的TypeScript集成，确保类型安全和可维护的代码架构。系统利用先进的基于WebGL的3D渲染引擎和自定义canvas实现，实现实时3D场景操作和高性能可视化。',
                '架构了复杂的微服务生态系统，包含五个专门的代码库：designhub-accounts-web用于用户认证和账户管理，designhub-common-core包含共享工具和业务逻辑，designhub-common-ui存放可重用UI组件，designhub-hub-web作为主要平台仪表板，ishot-editor-web提供核心3D编辑功能。每个服务都设计了清晰的关注点分离和健壮的API集成。',
                '核心3D编辑器具有先进的WebGL渲染功能，包括实时场景操作、材质编辑系统、协作编辑功能和云端项目同步。使用MobX存储实现了复杂的状态管理，包括编辑器、场景、渲染、材质和用户管理。系统支持复杂的3D工作流程，包括模型导入、纹理管理、光照控制和高质量渲染管道，并对处理大型3D资产进行了性能优化。',
                '实现了全面的DevOps实践，包括使用GitLab的自动化CI/CD流水线、多环境部署策略，以及使用pnpm工作空间和Turbo进行高效monorepo操作的先进包管理。利用Changesets进行版本管理和自动化npm包发布到私有注册表。系统具有健壮的错误处理、使用Vitest和Cypress的全面测试，以及用于最佳用户体验的渐进加载策略。',
                '项目展示了企业级前端开发能力，包括基于原子设计原则的组件驱动架构、先进的国际化支持、主题管理系统和无障碍功能。在敏捷环境中与后端工程师、3D图形专家和产品团队广泛协作，确保复杂3D工作流程与直观用户界面和健壮云基础设施的无缝集成。',
            ],
        },
        coordinates: [22.9951158, 113.3335372],
        location: 'Guangzhou, China',
        year: '2021-2023',
        links: {
            live: 'https://hub.realibox.com/',
        },
        img: [
            '/realibox/editor/editor.01.jpg',
            '/realibox/editor/editor.02.jpg',
            '/realibox/editor/editor.03.jpg',
            '/realibox/editor/realibox.00.jpg',
            '/realibox/editor/editor.04.jpg',
            '/realibox/editor/editor.05.jpg',
            '/realibox/editor/editor.06.jpg',
        ],
    },
    {
        type: {
            en: 'Full Stack',
            zh: '全栈开发',
        },
        tags: ['Data Engineer'],
        title: {
            en: 'Full Stack Developer',
            zh: '全栈开发工程师',
        },
        name: {
            en: 'Real-time AQI Platform',
            zh: '实时空气质量发布（大数据）平台',
        },
        company: 'Enshi Environmental Agency',
        description: {
            en: [
                'Real-time AQI Platform is a comprehensive air quality monitoring system that I developed for environmental health awareness. The platform combines advanced data engineering with modern web technologies to provide real-time air quality insights to the public. This full-stack application demonstrates my ability to build complex systems that handle real-time data processing, web scraping, and interactive visualizations.',
                'The backend is built with Spring Boot 2.4 and follows a robust microservices architecture. I implemented scheduled data collection tasks that automatically fetch XML data from government environmental APIs every 30 minutes for hourly data and daily at 10 AM for daily summaries. The system uses JDOM2 for XML parsing, cleaning and transforming raw environmental data into structured objects. MyBatis Plus handles database operations with MySQL 5.7 for persistent storage, while Redis provides caching and session management.',
                'The data pipeline is a key component that showcases my data engineering skills. XML web services provide data for multiple monitoring stations, measuring PM2.5, PM10, SO2, NO2, CO, and O3 levels. My custom data cleaning algorithms filter out invalid readings, handle missing values, and perform unit conversions. The system calculates AQI values, determines health risk levels, and generates multilingual health recommendations. All processed data is automatically stored with proper indexing for fast retrieval.',
                'I developed three different frontend applications to serve different user needs. The main public interface uses vanilla JavaScript with ECharts for data visualization, featuring real-time gauge charts, trend analysis, heatmaps, and geographical mapping. The admin panel is built with React 17 and Ant Design, providing comprehensive system management, user authentication with JWT tokens, operation logging, and statistical dashboards. I also created a Vue.js version for enhanced interactivity.',
                "The platform includes innovative health awareness features that set it apart from basic monitoring systems. I implemented real-time health alerts that change color coding based on AQI levels, from green for good air quality to maroon for hazardous conditions. The Web Speech API integration provides voice announcements in English, reading current AQI values, health implications, and cautionary statements. Users receive contextual health advice like 'suitable for outdoor activities' or 'sensitive groups should limit outdoor exposure'.",
                'The technical architecture demonstrates enterprise-level development practices. I used Swagger 2 for API documentation, implemented AES encryption for sensitive configuration data, and built comprehensive logging systems for monitoring data collection activities. The frontend uses Webpack for asset bundling, Axios for HTTP requests, and responsive CSS with AOS animations. The admin system features role-based access control, operation auditing, and real-time statistics. This project showcases my ability to build scalable, user-focused applications that combine technical complexity with practical public health benefits.',
            ],
            zh: [
                '实时AQI平台是我为环保健康意识开发的综合空气质量监测系统。该平台将先进的数据工程与现代网络技术相结合，为公众提供实时空气质量洞察。这个全栈应用展示了我构建复杂系统的能力，包括实时数据处理、网络爬虫和交互式可视化。',
                '后端使用Spring Boot 2.4构建，遵循稳健的微服务架构。我实现了定时数据收集任务，每30分钟自动从政府环保API获取XML数据进行小时数据更新，每日上午10点获取日度汇总。系统使用JDOM2进行XML解析，清洗和转换原始环境数据为结构化对象。MyBatis Plus处理MySQL 5.7的数据库操作，Redis提供缓存和会话管理。',
                '数据管道是展示我数据工程技能的关键组件。XML网络服务提供多个监测站点的数据，测量PM2.5、PM10、SO2、NO2、CO和O3等级。我的自定义数据清洗算法过滤无效读数，处理缺失值，执行单位转换。系统计算AQI值，确定健康风险等级，生成多语言健康建议。所有处理后的数据自动存储并建立适当索引以便快速检索。',
                '我开发了三个不同的前端应用来满足不同用户需求。主要公共界面使用原生JavaScript配合ECharts进行数据可视化，包含实时仪表盘图表、趋势分析、热力图和地理映射。管理面板使用React 17和Ant Design构建，提供全面的系统管理、JWT令牌用户认证、操作日志记录和统计仪表板。我还创建了Vue.js版本以增强交互性。',
                "平台包含创新的健康意识功能，使其区别于基础监测系统。我实现了基于AQI等级的实时健康警报，颜色编码从良好空气质量的绿色到危险状况的栗色。Web Speech API集成提供英语语音播报，朗读当前AQI值、健康影响和注意事项。用户收到上下文健康建议，如'适合户外活动'或'敏感人群应限制户外暴露'。",
                '技术架构展示了企业级开发实践。我使用Swagger 2进行API文档化，为敏感配置数据实现AES加密，构建全面的日志系统监控数据收集活动。前端使用Webpack进行资产打包，Axios处理HTTP请求，响应式CSS配合AOS动画。管理系统具有基于角色的访问控制、操作审计和实时统计。这个项目展示了我构建可扩展、以用户为中心的应用程序的能力，将技术复杂性与实际公共健康效益相结合。',
            ],
        },
        coordinates: [30.311395, 109.4795951],
        location: 'Enshi, Hubei, China',
        year: '2020',
        links: {
            live: 'https://aqi.eseemc.cn/',
        },
        img: [
            '/aqi/aqi01.jpg',
            '/aqi/aqi02.jpg',
            '/aqi/aqi03.jpg',
            '/aqi/aqi04.jpg',
            '/aqi/aqi05.jpg',
            '/aqi/aqi06.jpg',
            '/aqi/aqi07.jpg',
            '/aqi/aqi08.jpg',
            '/aqi/aqi09.jpg',
            '/aqi/aqi10.jpg',
            '/aqi/aqi11.jpg',
            '/aqi/aqi12.jpg',
            '/aqi/aqi13.jpg',
        ],
    },
    {
        type: {
            en: 'WebGL',
            zh: 'WebGL开发',
        },
        title: {
            en: 'Interactive 360° Virtual Tour Platform',
            zh: '交互式360°虚拟漫游平台',
        },
        name: {
            en: 'Real Estate VR Collections',
            zh: '房地产VR作品集',
        },
        company: 'Neuclear Stone Digital',
        description: {
            en: "During a 2-year contract period with Neuclear Stone Digital, a specialized 3D animation studio focused on architectural and interior design visualization, I developed comprehensive web-based virtual reality solutions for real estate marketing. As the lead web developer, I transformed their high-quality 3D renderings and HDR imagery into interactive, cross-platform virtual tour experiences accessible across all devices and browsers. Working closely with their design team, I converted Photoshop mockups into responsive HTML/CSS interfaces and integrated WebGL technology to showcase immersive 3D environments including residential apartments, luxury interiors, commercial buildings, and entire residential complexes. The platform features sophisticated 3D scene navigation with multiple camera positions, allowing users to explore different rooms and areas through intuitive click-based interactions. I implemented interactive hotspot systems with contextual popup information, seamless scene transitions, and dynamic viewpoint switching capabilities. Each virtual tour includes social media integration with API connectivity for sharing functionality, complete with JWT token authentication for secure access. The technical implementation encompasses responsive design principles ensuring optimal performance across desktop, tablet, and mobile devices, with specialized mobile features including click-to-call functionality and integrated navigation services. Additional multimedia capabilities include background music integration, video playback systems, and comprehensive cross-browser compatibility testing. All applications were deployed and maintained on Alibaba Cloud EC2 servers with custom domain configurations. Throughout this engagement, I successfully delivered 17+ individual virtual tour projects spanning multiple provinces across China, establishing a scalable development framework that significantly enhanced the company's service offerings and client engagement capabilities.",
            zh: '在与专注于建筑和室内设计可视化的3D动画工作室Neuclear Stone Digital为期2年的合同期间，我开发了用于房地产营销的综合性网络虚拟现实解决方案。作为首席网络开发人员，我将他们的高质量3D渲染图和HDR图像转换为可在所有设备和浏览器上访问的交互式跨平台虚拟导览体验。与他们的设计团队密切合作，我将Photoshop模拟图转换为响应式HTML/CSS界面，并集成WebGL技术展示沉浸式3D环境，包括住宅公寓、豪华室内设计、商业建筑和整个住宅小区。该平台具有复杂的3D场景导航功能，支持多个摄像机位置，允许用户通过直观的点击交互探索不同的房间和区域。我实现了带有上下文弹出信息的交互式热点系统、无缝场景切换和动态视点切换功能。每个虚拟导览都包括社交媒体集成，具有用于分享功能的API连接，配备JWT令牌认证确保安全访问。技术实现涵盖响应式设计原则，确保在桌面、平板和移动设备上的最佳性能，包括专门的移动功能如点击拨号和集成导航服务。其他多媒体功能包括背景音乐集成、视频播放系统和全面的跨浏览器兼容性测试。所有应用程序都部署并维护在阿里云EC2服务器上，配有自定义域名配置。在整个合作期间，我成功交付了17+个跨越中国多个省份的个人虚拟导览项目，建立了可扩展的开发框架，显著增强了公司的服务产品和客户参与能力。',
        },
        coordinates: [30.2888597, 109.4846285],
        location: 'Multiple Provinces, China',
        year: '2020-2021',
        img: [
            '/vr/fhjy.jpg',
            '/vr/changpingli.jpg',
            '/vr/dalincheng.jpg',
            '/vr/gyyh.jpg',
            '/vr/htfxj.jpg',
            '/vr/jhhy.jpg',
            '/vr/jlw.jpg',
            '/vr/jxmm.jpg',
            '/vr/jsjxmm.jpg',
            '/vr/pzf.jpg',
            '/vr/tf.jpg',
            '/vr/wjsf.jpg',
            '/vr/xcsd.jpg',
            '/vr/ybhf.jpg',
            '/vr/ysxc.jpg',
            '/vr/zyyc.jpg',
            '/vr/tsyhy.jpg',
        ],
    },
    {
        type: {
            en: 'Website',
            zh: '网站开发',
        },
        title: {
            en: 'Corporate Website Development Platform',
            zh: '企业网站开发平台',
        },
        name: {
            en: 'Enterprises Portal Collections',
            zh: '企业门户作品集',
        },
        company: 'Day Digital',
        description: {
            en: 'Comprehensive enterprise web development solution encompassing both public-facing corporate websites and sophisticated internal business systems across diverse industries. Working with Day Digital, I developed multi-faceted web applications serving government agencies, healthcare institutions, tourism bureaus, and private enterprises throughout the project lifecycle. The portfolio spans from traditional corporate websites built with CMS platforms to complex internal enterprise systems utilizing ASP.NET and PHP technologies. For healthcare sector clients, I implemented specialized systems including patient health examination report query platforms with secure database integration, comprehensive appointment scheduling systems with real-time availability management, and patient portal interfaces. Corporate clients received tailored internal office management systems featuring employee workflow automation, document management, and inter-departmental communication tools. Additionally, I developed specialized applications including auction platforms for numismatic collections with bidding mechanisms and payment gateway integration, and construction engineering measurement data query systems with GPS coordinate mapping and project tracking capabilities. Each project required custom database architecture design, responsive UI implementation from design mockups, user authentication and authorization systems, and comprehensive deployment management across multiple production servers. The technical implementation involved extensive work with content management systems, database optimization, API integrations, and cross-platform compatibility ensuring seamless operation across desktop and mobile environments. All systems included administrative dashboards, data export capabilities, and robust security measures including role-based access control and data encryption protocols.',
            zh: '涵盖面向公众的企业网站和复杂内部业务系统的综合性企业网络开发解决方案，服务于各个行业。与Day Digital合作期间，我为政府机构、医疗机构、旅游局和私营企业开发了多方面的网络应用程序，覆盖项目全生命周期。项目组合从使用CMS平台构建的传统企业网站扩展到使用ASP.NET和PHP技术的复杂内部企业系统。为医疗行业客户，我实施了专门的系统，包括带有安全数据库集成的患者健康体检报告查询平台、具有实时可用性管理的综合预约挂号系统，以及患者门户界面。企业客户获得了定制的内部办公管理系统，具有员工工作流程自动化、文档管理和部门间沟通工具。此外，我还开发了专门的应用程序，包括具有竞价机制和支付网关集成的钱币收藏品拍卖平台，以及具有GPS坐标映射和项目跟踪功能的建筑工程测量数据查询系统。每个项目都需要自定义数据库架构设计、从设计稿实现响应式UI、用户认证和授权系统，以及跨多个生产服务器的全面部署管理。技术实现涉及内容管理系统的大量工作、数据库优化、API集成和跨平台兼容性，确保在桌面和移动环境中的无缝操作。所有系统都包括管理仪表板、数据导出功能和强大的安全措施，包括基于角色的访问控制和数据加密协议。',
        },
        coordinates: [30.297884, 109.4955927],
        location: 'Enshi, Hubei, China',
        year: '2019',
        link: 'https://www.es9e.cn/',
        img: [
            '/website/tenglongdong.jpg',
            '/website/enshitusicheng01.jpg',
            '/website/enshitusicheng02.jpg',
            '/website/yangshegnhefeng.jpg',
            '/website/es9e.jpg',
            '/website/enshizhoubowuguan.jpg',
            '/website/enshizhousheyingjiaxiehui.jpg',
        ],
    },
    {
        type: {
            en: 'Mobile Apps',
            zh: '移动应用',
        },
        title: {
            en: 'FitsGo',
            zh: 'FitsGo',
        },
        name: {
            en: 'FitsGo',
            zh: 'FitsGo 健身追踪',
        },
        company: 'Otago Polytechnic',
        description: {
            en: 'A comprehensive fitness tracking mobile application designed to encourage people to start exercising by providing interactive map-based workout experiences. Built as a cross-platform app using React Native and Firebase, FitsGo allows users to select exercise routes from nearby points of interest, track their workouts (running, walking, cycling) with real-time GPS monitoring, and earn badges for visiting locations. Features include user authentication, profile management with weight/age tracking, real-time calorie calculation based on MET values, workout history with detailed statistics, and social elements for future friend connectivity and weekly challenges.',
            zh: '一个综合性健身追踪移动应用程序，旨在通过提供基于地图的交互式锻炼体验来鼓励人们开始锻炼。使用React Native和Firebase构建的跨平台应用，FitsGo允许用户从附近的兴趣点选择锻炼路线，通过实时GPS监控跟踪锻炼（跑步、步行、骑行），并通过访问位置获得徽章。功能包括用户认证、带有体重/年龄跟踪的个人资料管理、基于MET值的实时卡路里计算、带有详细统计的锻炼历史，以及未来朋友连接和每周挑战的社交元素。',
        },
        coordinates: [-45.8750186, 170.4973482],
        location: 'Dunedin, New Zealand',
        year: '2019',
        links: {
            github: 'https://github.com/aemooooon/FitsGo',
        },
        img: [
            '/fitsgo/fitsgo.01.gif',
            '/fitsgo/fitsgo.02.jpg',
            '/fitsgo/fitsgo.03.jpg',
            '/fitsgo/fitsgo.04.jpg',
            '/fitsgo/fitsgo.05.jpg',
            '/fitsgo/fitsgo.06.jpg',
            '/fitsgo/fitsgo.07.jpg',
            '/fitsgo/fitsgo.08.jpg',
            '/fitsgo/fitsgo.09.jpg',
            '/fitsgo/fitsgo.10.jpg',
        ],
    },
    {
        type: {
            en: 'Mobile Apps',
            zh: '移动应用',
        },
        title: {
            en: 'Travel Assistant',
            zh: '旅行助手',
        },
        name: {
            en: 'Travel Assistant',
            zh: '智能旅行助手',
        },
        company: 'Otago Polytechnic',
        description: {
            en: 'An Android-based travel companion application built with Kotlin and Room Database, designed to help travelers explore unfamiliar countries with confidence. The app features interactive Google Maps integration with clustered location markers, country selection dropdown, real-time location services, and multilingual phrase translation using Yandex API. Built using modern Android architecture components including ViewModel, LiveData, Coroutines, and View/Data Binding, with comprehensive documentation generated using Dokka and UI testing implemented with Espresso. The application provides curated lists of top-rated attractions and landmarks for each country, complete with coordinates and detailed information.',
            zh: '一个基于Android的旅行伴侣应用程序，使用Kotlin和Room数据库构建，旨在帮助旅行者自信地探索陌生的国家。该应用程序具有与聚类位置标记的交互式Google Maps集成、国家选择下拉菜单、实时位置服务，以及使用Yandex API的多语言短语翻译功能。使用现代Android架构组件构建，包括ViewModel、LiveData、协程和视图/数据绑定，使用Dokka生成全面的文档，并使用Espresso实现UI测试。该应用程序为每个国家提供精选的顶级景点和地标列表，包含坐标和详细信息。',
        },
        coordinates: [-45.8750186, 170.4973482],
        location: 'Dunedin, New Zealand',
        year: '2019',
        links: {
            github: 'https://github.com/aemooooon/Travel-Assistant',
        },
        img: [
            '/travelassistant/ta01.jpg',
            '/travelassistant/ta02.jpg',
            '/travelassistant/ta03.jpg',
            '/travelassistant/ta04.jpg',
            '/travelassistant/ta05.jpg',
            '/travelassistant/ta06.jpg',
            '/travelassistant/ta07.jpg',
            '/travelassistant/ta08.jpg',
        ],
    },
    {
        type: {
            en: 'Full Stack',
            zh: '全栈开发',
        },
        tags: ['Data Engineer'],
        title: {
            en: 'ECAN Data Pipeline',
            zh: 'ECAN数据管道',
        },
        name: {
            en: 'ECAN Data Pipeline',
            zh: '坎特伯雷环境数据管道',
        },
        company: 'University of Canterbury',
        description: {
            en: [
                "ECAN Data Pipeline represents a large-scale collaborative data engineering project involving 22 students from the DATA472 course (Cloud Computing and Infrastructure Data Engineering) at University of Canterbury. I served as one of three core volunteer developers responsible for architecting and implementing the central data collection infrastructure. The project was initiated by a requirement from an ECAN (Environment Canterbury) employee who was also a student in our instructor's program, creating a real-world data engineering challenge for environmental monitoring in Canterbury.",
                "As the technical lead for backend infrastructure, I designed and implemented a comprehensive Apache Airflow-based data collection service that orchestrates automated ETL pipelines for over 20 individual student datasets. Each student sourced their own environmental data from ECAN's open data portal, and I created standardized data ingestion processors that handle diverse data formats including CSV, JSON, and XML. The Airflow DAGs run on scheduled intervals using CRON expressions, with daily and hourly collection patterns depending on data source requirements.",
                "The architecture utilizes AWS cloud infrastructure extensively, with PostgreSQL databases deployed on AWS RDS for centralized data storage and Express.js API services running on EC2 instances. I developed a Node.js Web API service with comprehensive Swagger documentation that provides RESTful endpoints for each student's dataset. The API implements proper error handling, Winston logging, and CORS configuration to support multiple frontend applications. Each student has their own dedicated route and processor, allowing for modular data management while maintaining system cohesion.",
                'My role extended beyond technical implementation to include mentoring non-IT background students in data engineering concepts and best practices. I provided guidance on data cleaning techniques, database schema design, and API development while ensuring all contributions followed standardized patterns. The PostgreSQL database schema accommodates various environmental data types including air quality measurements, water quality indicators, and meteorological data, with proper indexing and foreign key relationships for optimal query performance.',
                'The system demonstrates advanced DevOps practices with automated deployment pipelines, environment configuration management using dotenv, and comprehensive logging across all services. I implemented data validation layers that ensure data quality and consistency across diverse student contributions. The Airflow web interface provides monitoring capabilities for all DAG executions, with detailed logs and error tracking. The project successfully aggregated environmental data from Canterbury region, enabling comprehensive analysis of air quality, water quality, and climate patterns.',
                'Beyond the core infrastructure, I contributed to multiple visualization components including Python Streamlit dashboards and GraphQL APIs for flexible data querying. The project showcases enterprise-level data engineering skills including microservices architecture, cloud deployment, automated testing, and collaborative development workflows. This experience demonstrates my ability to lead technical teams, architect scalable data systems, and deliver complex projects that bridge academic learning with real-world environmental monitoring requirements.',
            ],
            zh: [
                'ECAN数据管道代表了一个大规模协作数据工程项目，涉及坎特伯雷大学DATA472课程（云计算和基础设施数据工程）的22名学生。我担任三名核心志愿开发者之一，负责架构和实施中央数据收集基础设施。该项目由ECAN（坎特伯雷环境局）员工发起，他也是我们导师项目的学生，为坎特伯雷环境监测创造了真实世界的数据工程挑战。',
                '作为后端基础设施的技术负责人，我设计并实施了基于Apache Airflow的综合数据收集服务，为超过20个学生个人数据集编排自动化ETL管道。每个学生从ECAN开放数据门户获取自己的环境数据，我创建了处理多样化数据格式（包括CSV、JSON和XML）的标准化数据摄取处理器。Airflow DAGs使用CRON表达式按计划间隔运行，根据数据源要求采用每日和每小时收集模式。',
                '架构广泛使用AWS云基础设施，PostgreSQL数据库部署在AWS RDS上进行集中数据存储，Express.js API服务运行在EC2实例上。我开发了带有完整Swagger文档的Node.js Web API服务，为每个学生的数据集提供RESTful端点。API实现了适当的错误处理、Winston日志记录和CORS配置，以支持多个前端应用程序。每个学生都有自己专用的路由和处理器，允许模块化数据管理同时保持系统凝聚力。',
                '我的角色超越了技术实施，还包括指导非IT背景学生学习数据工程概念和最佳实践。我在数据清洗技术、数据库架构设计和API开发方面提供指导，同时确保所有贡献遵循标准化模式。PostgreSQL数据库架构适应各种环境数据类型，包括空气质量测量、水质指标和气象数据，具有适当的索引和外键关系以优化查询性能。',
                '系统展示了先进的DevOps实践，包括自动化部署管道、使用dotenv的环境配置管理和所有服务的全面日志记录。我实现了数据验证层，确保多样化学生贡献的数据质量和一致性。Airflow网络界面为所有DAG执行提供监控功能，具有详细日志和错误跟踪。该项目成功聚合了坎特伯雷地区的环境数据，实现了空气质量、水质和气候模式的综合分析。',
                '除了核心基础设施，我还为多个可视化组件做出贡献，包括Python Streamlit仪表板和用于灵活数据查询的GraphQL API。该项目展示了企业级数据工程技能，包括微服务架构、云部署、自动化测试和协作开发工作流程。这一经验展示了我领导技术团队、架构可扩展数据系统以及交付连接学术学习与真实世界环境监测要求的复杂项目的能力。',
            ],
        },
        coordinates: [-43.5357406, 172.6358119],
        location: 'Christchurch, New Zealand',
        year: '2024',
        links: {
            github: 'https://github.com/aemooooon/DATA472-Individual-Project-Submission',
        },
        img: [
            '/data472/v1.gif',
            '/data472/v2.gif',
            '/data472/472.jpg',
            '/data472/af01.jpg',
            '/data472/datapipeline.jpg',
            '/data472/FuelPriceData.jpg',
            '/data472/GasStationData.jpg',
            '/data472/ProjectManagement.jpg',
            '/data472/services.jpg',
            '/data472/WebApiResponse.jpg',
        ],
    },
    {
        type: {
            en: 'Activity',
            zh: '社区活动',
        },
        title: {
            en: 'Assisted IT Meetups',
            zh: '协会志愿者',
        },
        company: 'CITANZ',
        name: {
            en: 'CITANZ CHCH Events',
            zh: 'CITANZ基督城活动',
        },
        description: {
            en: 'Active volunteer contributor to CITANZ (Chinese Information Technology Association of New Zealand) Christchurch chapter, facilitating monthly IT community meetups that bring together professionals, students, and technology enthusiasts. Serve as both speaker and engaged listener, sharing technical expertise on software development, data engineering, and emerging technologies while learning from diverse industry perspectives. Actively mentor newcomers to the tech industry, providing guidance on career development, technical skills, and industry best practices. Foster collaborative learning environments through organizing workshops, panel discussions, and networking sessions that strengthen the local tech community. Contribute to knowledge exchange initiatives by facilitating discussions on current technology trends, helping members solve technical challenges, and connecting professionals across different specializations. This volunteer work exemplifies the spirit of giving back to the community while continuously growing through peer learning and mentorship opportunities.',
            zh: '作为新西兰计算机和信息技术协会(CITANZ)基督城分会的积极志愿者，协助举办月度IT社区聚会，汇聚专业人士、学生和技术爱好者。既担任演讲者又是积极的倾听者，分享软件开发、数据工程和新兴技术方面的专业知识，同时从多元化的行业视角中学习。积极指导技术行业新人，在职业发展、技术技能和行业最佳实践方面提供指导。通过组织研讨会、小组讨论和网络交流会，营造协作学习环境，加强本地技术社区建设。通过促进当前技术趋势讨论、帮助成员解决技术挑战、连接不同专业领域的专业人士，为知识交流倡议做出贡献。这项志愿工作体现了回馈社区的精神，同时通过同伴学习和导师机会持续成长。',
        },
        coordinates: [-43.5828903, 172.5695089],
        location: 'Halswell Library, Christchurch',
        year: '2024-2025',
        links: {
            official: 'https://www.cita.org.nz/',
        },
        img: [
            '/citanz/cita-00.jpg',
            '/citanz/cita-01.jpg',
            '/citanz/cita-02.jpg',
            '/citanz/cita-03.jpg',
            '/citanz/cita-04.jpg',
            '/citanz/cita-04.5.jpg',
            '/citanz/cita-05.jpg',
            '/citanz/cita-06.jpg',
            '/citanz/cita-07.jpg',
            '/citanz/cita-08.jpg',
            '/citanz/cita-09.jpg',
        ],
    },
    {
        type: {
            en: 'Activity',
            zh: '社区活动',
        },
        title: {
            en: 'Save Kiwi',
            zh: '拯救奇异鸟',
        },
        name: {
            en: 'AI Hackathon 2024',
            zh: '2024年AI黑客松',
        },
        company: 'University of Canterbury',
        description: {
            en: 'Design an AI solution to help existing organizations improve maintenance and analysis efficiency to better protect kiwi birds. It uses advanced tech to protect kiwi birds by combining smart cages, edge computing, and cloud analytics. Smart cages with RGB cameras monitor wildlife, while edge computing processes images in real-time using a vision-transformer model. This model distinguishes between kiwi birds, predators, and non-threatening animals. Predators are captured; others are released. Data is sent to a cloud platform for monitoring and alerts, enabling quick conservation responses.',
            zh: '设计一个AI解决方案，帮助现有组织提高维护和分析效率，更好地保护奇异鸟。它通过结合智能笼子、边缘计算和云分析等先进技术来保护奇异鸟。带有RGB摄像头的智能笼子监控野生动物，边缘计算使用视觉变换器模型实时处理图像。该模型区分奇异鸟、捕食者和非威胁动物。捕食者被捕获，其他动物被释放。数据发送到云平台进行监控和警报，实现快速保护响应。',
        },
        coordinates: [-43.5218726, 172.5674936],
        location: 'University of Canterbury',
        year: '2024',
        links: {
            official: 'https://aihackathon.nz/ai-hackathon-2024/',
        },
        img: [
            '/f4/f4.3.jpg',
            '/f4/f4.jpg',
            '/f4/f4.1.jpg',
            '/f4/f4.2.jpg',
            '/f4/f4.4.jpg',
            '/f4/f4.5.jpg',
            '/f4/f4.6.jpg',
        ],
    },
];
