#!/bin/bash

echo "🛠️  手动图片格式转换指南"
echo "=========================="
echo ""
echo "由于需要安装额外工具，以下是手动转换方案："
echo ""
echo "📦 1. 安装必要工具："
echo "   brew install imagemagick"
echo "   brew install libavif"
echo ""
echo "🔄 2. 转换命令 (在public/cube-textures目录下运行)："
echo ""
echo "   # 创建目录"
echo "   mkdir -p ../cube-textures-webp"
echo "   mkdir -p ../cube-textures-avif"
echo ""
echo "   # 转换为WebP (质量85%)"
echo "   for file in *.jpg; do"
echo "     magick \"\$file\" -quality 85 \"../cube-textures-webp/\${file%.*}.webp\""
echo "   done"
echo ""
echo "   # 转换为AVIF (质量60%)"
echo "   for file in *.jpg; do"
echo "     avifenc -q 60 \"\$file\" \"../cube-textures-avif/\${file%.*}.avif\""
echo "   done"
echo ""
echo "🎯 3. 在线转换工具 (推荐)："
echo "   - https://squoosh.app/ (Google开发的图片压缩工具)"
echo "   - https://tinypng.com/ (支持WebP)"
echo "   - https://avif.io/ (AVIF转换)"
echo ""
echo "📊 4. 预期效果："
echo "   - WebP: 文件大小减少 25-50%"
echo "   - AVIF: 文件大小减少 50-70%"
echo ""
echo "✨ 转换完成后，代码会自动检测并使用最优格式！"

# 检查当前cube-textures的大小
if [ -d "../public/cube-textures" ]; then
    echo ""
    echo "📁 当前cube-textures目录："
    ls -lh ../public/cube-textures/*.jpg 2>/dev/null || echo "   没有找到JPG文件"
    echo ""
    echo "📏 目录总大小："
    du -sh ../public/cube-textures 2>/dev/null || echo "   无法计算大小"
fi
